jeep_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from jeep_inventory.forms import UserLoginForm
from jeep_inventory.models import User, db
from werkzeug.security import check_password_hash

from flask_login import login_user, logout_user, current_user, login_required 

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
     
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            print(email, username)

            user = User(email, username, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have succesfully created a user account {username}', 'user-created')

            return redirect(url_for('auth.signin'))
        
    except:
        raise Exception('Invalid Form Data: Please check your form') 
    return render_template('signup.html', form = form )

    

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    try: 
        if request.method == 'POST' and form.validate_on_submit(): 
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                print(f"this is the logged user {logged_user}")
                login_user(logged_user)
                flash(f"You were successfully logged in: Via email/password", 'auth-success')
                return redirect(url_for('site.profile'))
            
            else:
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
        
    except:
        raise Exception('Invalid Form Data: Please Check Your Form!')
    return render_template('signin.html', form = form)

jeep_inventory/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from jeep_inventory.forms import JeepForm
from jeep_inventory.models import Jeep, db
from jeep_inventory.helpers import random_joke_generator

site = Blueprint('site', __name__, template_folder='site_templates')



@site.route('/')
def home():
    print("It's Magic time!")
    return render_template('index.html')

@site.route('/profile', methods = ['GET','POST'])
@login_required 
def profile():
    # random_joke_generator()
    my_jeep = JeepForm()

    try:
        if request.method == "POST" and my_jeep.validate_on_submit():
            name = my_jeep.name.data
            description = my_jeep.description.data
            price = my_jeep.price.data
            tire_quality = my_jeep.tire_quality.data
            drive_time = my_jeep.drive_time.data
            max_speed = my_jeep.max_speed.data
            height = my_jeep.height.data
            weight = my_jeep.weight.data
            cost_of_production = my_jeep.cost_of_production.data
            series = my_jeep.series.data
            if my_jeep.dad_joke.data:
                random_joke = my_jeep.dad_joke.data
            else:
                random_joke = random_joke_generator()          
            user_token = current_user.token

            jeep = Jeep(name, description, price, tire_quality, drive_time, max_speed, height, weight, cost_of_production, series, random_joke, user_token)

            db.session.add(jeep)
            db.session.commit()

            return redirect(url_for('site.profile'))
    except:
        raise Exception("Jeep not created, please check your form and try again!")
    
    current_user_token = current_user.token

    jeeps = Jeep.query.filter_by(user_token=current_user_token)

    
    return render_template('profile.html', form=my_jeep, jeeps = jeeps )

jeep_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Jeep API</title>
</head>
<body>

    <!-- Nav Bar  -->
    <nav class="ct-nav">

        <div>
            <img src="../static/images/jeeplogo.png" alt="jeep logo">
        </div>

        <div>
           <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>Jeep Project</li>

                </a>
                <a href="{{ url_for('site.home') }}">
                    <li>Donate</li>

                </a>
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>

                </a>
                <a href="#">
                    <li>Log Out</li>

                </a>
                <a href="{{ url_for('auth.signin')  }}">
                    <li>Sign In</li>

                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up</li>

                </a>
           </ul>
        </div>

    </nav>

    {% block content %}

    <!-- other content lives here  -->

    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

jeep_inventory/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Place Username Here... ") }}
        </fieldset>
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here... ") }}
        </fieldset>
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password Here... ") }}
        </fieldset>

        {{ form.submit_button(class="btn btn-primary btn-block mt-2") }}

    </div>




</form>

jeep_inventory/templates/jeep_form.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="name-field">
            {{ form.name.label }}            
            {{ form.name(class = "form-control", placeholder="Name") }}
        </fieldset>
        <fieldset id="description-field">
            {{ form.description.label }}            
            {{ form.description(class = "form-control", placeholder="Description") }}
        </fieldset>
        <fieldset id="price-field">
            {{ form.price.label }}            
            {{ form.price(class = "form-control", placeholder="Price") }}
        </fieldset>
        <fieldset id="tire-field">
            {{ form.tire_quality.label }}            
            {{ form.tire_quality(class = "form-control", placeholder="Tire Quality") }}
        </fieldset>
        <fieldset id="drive-field">
            {{ form.drive_time.label }}            
            {{ form.drive_time(class = "form-control", placeholder="Drive Time") }}
        </fieldset>
        <fieldset id="speed-field">
            {{ form.max_speed.label }}            
            {{ form.max_speed(class = "form-control", placeholder="Max Speed") }}
        </fieldset>
        <fieldset id="height-field">
            {{ form.height.label }}            
            {{ form.height(class = "form-control", placeholder="Height") }}
        </fieldset>
        <fieldset id="weight-field">
            {{ form.weight.label }}            
            {{ form.weight(class = "form-control", placeholder="Weight") }}
        </fieldset>
        <fieldset id="cop-field">
            {{ form.cost_of_production.label }}            
            {{ form.cost_of_production(class = "form-control", placeholder="Cost of Production") }}
        </fieldset>
        <fieldset id="series-field">
            {{ form.series.label }}            
            {{ form.series(class = "form-control", placeholder="Series") }}
        </fieldset>
        <fieldset id="dadjoke-field">
            {{ form.dad_joke.label }}            
            {{ form.dad_joke(class = "form-control", placeholder="Dad Joke") }}
        </fieldset>


        <!-- Submit Button Area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2") }}

    </div>   
</form>